# Generated by Django 4.1.1 on 2022-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_school_max_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='max_students',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
